micronaut:
  application:
    name: student
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger
        mapping: /swagger/*
      swagger-ui:
        paths:
          - classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
---
micronaut:
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${ACCESS_TOKEN_SECRET:thisIsASecretKeyForLocalDevelopment}
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: ${REFRESH_TOKEN_SECRET:thisIsASecretKeyForLocalDevelopment}
---
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        proc:
          param_null_passing: true
        hbm2ddl:
          auto: update
        show_sql: true
---
netty:
  default:
    allocator:
      max-order: 3
---
jackson:
  serializationInclusion: ALWAYS
---
datasources:
  default:
    pool-name: he-hikari-pool
    maximum-pool-size: 2
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_ENDPOINT:127.0.0.1}:5432/${DATABASE_NAME:student}
    username: ${DATABASE_USER:student_user}
    password: ${DATABASE_PASSWORD:pwd1235}
