CREATE TABLE IF NOT EXISTS ${schemaName}.students (
  StudentId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  MiddleName VARCHAR(50),
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(256) NOT NULL,
  Created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);