version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: pwd1235
      POSTGRES_DB: student
    ports:
      - "5432:5432"

